# -*- coding: utf-8 -*-
"""SGD_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKu3vOebJ0nSw1bg98Fwn63UkTqjq9j3
"""

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
import joblib
from google.colab import drive
drive.mount('/content/drive')

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

#with tf.device('/GPU:0'):
file = "/content/drive/My Drive/dataset_6k.csv"
dataset = pd.read_csv(file)

X = dataset.drop('label', axis=1)
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

params = {
    "loss": ["hinge", "log_loss", "modified_huber", "perceptron"],
    "alpha": [0.001, 0.01, 0.1],
    "penalty": ["l2", "elasticnet", None],
    "class_weight": ['balanced'],
    "max_iter": [1000, 1500, 2000, 2500]
}

model = SGDClassifier()

model_cv = GridSearchCV(model, param_grid=params, cv=10, scoring='accuracy')

model_cv.fit(X_train, y_train)

best_params = model_cv.best_params_
best_estimator = model_cv.best_estimator_

saved_model = joblib.dump(best_estimator, "/content/drive/My Drive/sgd_model.joblib")
# Make predictions
y_pred = best_estimator.predict(X_test)

acc_score = accuracy_score(y_test, y_pred)

print("Prediction on test dataset: {}".format(acc_score))

print(best_params)
print(best_estimator)